# Based on https://github.com/actions/starter-workflows/blob/56c93ff7521bd818b4186cd504aba6e2b7b42643/ci/python-app.yml

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Workflow это по сути последовательность действий, которая выполняется по
# каким-то определенным условиям.
#
# Например, можно автоматически запускать тесты, на PR'ы или при мерже в мастер.
# Таким образом можно гарантировать, что очередные наши изменения ничего не сломали.
#
# Workflow на github'е описываются в файле формата YAML (см. https://yaml.org/) по определенному формату.
# Полное описание синтаксиса для github'а есть здесь: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# Но и без него всё должно быть довольно понятно.

name: Run tests and show coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # На каждое выполнение job'ы будет автоматически создана новая виртуальная машина с последней версией Ubuntu
    # На ней и будут выполняться последующие шаги.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Check coverage
      # Здесь --cov=minesweeper выбирает директорию, для которой считать покрытие тестами
      run: |
        pytest --cov=minesweeper
      # Дополнительно можно запустить pytest --cov=minesweeper --cov-report html:cov_html
      # И научиться загружать отчёт из папки cov_html в артифакты workflow
      # В этом поможет пример из документации:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#packaging-workflow-data-as-artifacts
